name: Test Self-Hosted Runner

on: [push]

jobs:
  test-runner:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display System Info
        run: |
          echo "Running on $(uname -s) $(uname -r)"
          echo "==================================="
          echo "CPU: $(nproc) cores"
          echo "==================================="
          echo "Write-Host Displaying System Info:"
          if (Get-Command free -ErrorAction SilentlyContinue) {
            free -h 
          } else {
            Write-Host Memory info Unavailable.
          }

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt || echo "No such file is found."

      - name: Sample
        run: |
          echo "Testing python versions on self-hosted runner"
          python --version
          echo "All tests have passed."
