name: Test Self-Hosted Runner

on: [push]

jobs:
  test-runner:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display System Info
        run: |
          Write-host "Displaying System Info:"
          # Get operating system
          $osInfo = Get-CimInstance Win32_OperatingSystem
          Write-Host "Running on $($osInfo.Caption) Version $($osInfo.Version)"
          
          # Free physical memory is returned in kilobytes
          $freeMemoryKB = $os.FreePhysicalMemory
          echo $freeMemoryKB
          
          # Convert free memory to MB
          $freeMemoryMB = [Math]::Round($freeMemoryKB / 1024, 2)
          echo $freeMemoryMB

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          try {
            python -m pip install -r requirements.txt
          }
          catch {
            echo "No such file is found."
          }

      - name: Sample
        run: |
          echo "Testing python versions on self-hosted runner"
          python --version
          echo "All tests have passed."
